[tool.poetry]
name = "aga"
version = "0.1.0"
description = "aga grades assignments"
authors = ["Riley Shahar <riley.shahar@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"
pytest-cov = "^2.12.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
